services:
  db:
    image: postgres:16-alpine
    container_name: sgpd_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sgpd
      POSTGRES_USER: sgpd_user
      POSTGRES_PASSWORD: "1754298626"
      TZ: "America/Guayaquil"
    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sgpd_user -d sgpd"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
